/* cria novo banco */
CREATE DATABASE IF NOT EXISTS teste01;
/* usando o banco que criamos */
USE teste01;
/* mostra databases criados */
SHOW DATABASES;
/* cria nova tabela caso a mesma nao exista*/
CREATE TABLE IF NOT EXISTS fornecedor (
IDFORNECEDOR INT AUTO_INCREMENT,
NOME VARCHAR(45),
ENDERECO VARCHAR(45),
TELEFONE INT,
CIDADE VARCHAR(20) DEFAULT 'SAO PAULO',
EMAIL VARCHAR(25) UNIQUE,
PRIMARY KEY (IDFORNECEDOR)
);

/* mostra tabelas criadas */
SHOW TABLES;

CREATE TABLE IF NOT EXISTS PRODUTO (
IDPRODUTO INT NOT NULL,
DESCRICAO VARCHAR(45),
PRECO DECIMAL(7, 2),
UNIDADE VARCHAR(10),
IDFORNECEDOR INT NOT NULL,
PRIMARY KEY (IDPRODUTO),
FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);

SHOW TABLES;

/* eliminar banco de dados */
/* DROP DATABASE EXEMPLO -- CUIDADO!! */

/* inserir dados de fornecedor */
INSERT INTO FORNECEDOR VALUES (
1, 'PAPEL RECICLADO', 'RUA BRASIL, 100', 4441212, 'BRAGANCA PAULISTA', 'RECI@MAIL'
);

INSERT INTO FORNECEDOR VALUES (
IDFORNECEDOR, 'CASA BAHIA', 'RUA DO MERCADO, 200', 40338787, 'BRAGANCA PAULISTA', 'CASABAHIA@GMAIL.COM'
),
(IDFORNECEDOR, 'LOJA CEM', 'RUA DO COMERCIO, 2800', 457888776, 'ATIBAIA', 'LOJACEM@GMAIL.COM'),
(IDFORNECEDOR, 'MAGAZINE LUIZA', 'RUA DAS ALEGRIAS, 9000', 87654393, 'ATIBAIA', 'MAGAZINELUIZA@GMAIL.COM');
SELECT * FROM FORNECEDOR;

INSERT INTO PRODUTO VALUES (
100, 'FOGAO', 800.50, 'PC', 2),
(110, 'GELADEIRA', 200.70, 'PC', 1),
(150, 'FOGAO COOKTOP', 1340.78, 3),
(160, 'AR CONDICIONADO', 1800, 'PC', 4);